./bin/Makefile
./config/Makefile
./haldriver/comm_hayes_modem/Makefile
./haldriver/comm_net_tcpip/Makefile
./haldriver/comm_net_tcpip6/Makefile
./haldriver/comm_scup_485/Makefile
./haldriver/comm_std_serial/Makefile
./haldriver/comm_virtual_port/Makefile
./haldriver/flash_storage/Makefile
./haldriver/Makefile
./haldriver/ui_base/Makefile
./lib/applog/Makefile
./lib/comm_base/Makefile
./lib/config_parser/Makefile
./lib/data_exchange/Makefile
./lib/data_mgmt/Makefile
./lib/Makefile
./lib/publib/Makefile
./lib/security_manage/Makefile
./log/Makefile
./mainapp/config_mgmt/Makefile
./mainapp/equip_mon/Makefile
./mainapp/Makefile
./mainapp/splash/Makefile
./mainapp/time_sync/Makefile
./maintenance/Makefile
./Makefile
./sampler/can_sampler/Makefile
./sampler/eem_csu/Makefile
./sampler/i2c_sampler/Makefile
./sampler/main_board/Makefile
./sampler/Makefile
./sampler/rs485_sampler/Makefile
./sampler/sampler_base/Makefile
./service/eem_soc/Makefile
./service/gen_ctl/Makefile
./service/lcd_ui/Makefile
./service/lcd_ui_mini/Makefile
./service/mail/Makefile
./service/maintenance_intf/Makefile
./service/Makefile
./service/modbus/Makefile
./service/plc/Makefile
./service/simple_service/Makefile
./service/sms/Makefile
./service/snmpv3_agent/Makefile
./service/snmp_agent/Makefile
./service/web_ui/Makefile
./service/web_user/Makefile
./service/ydn23/Makefile
./systemhandler/Makefile
